// NOTE: https://github.com/countries/countries のデータを参照
export const COUNTRIES = [
  { en: "Andorra", ja: "アンドラ", alpha2: "AD", lowerAlpha2: "ad", code: 376 },
  {
    en: "United Arab Emirates",
    ja: "アラブ首長国連邦",
    alpha2: "AE",
    lowerAlpha2: "ae",
    code: 971,
  },
  { en: "Afghanistan", ja: "アフガニスタン", alpha2: "AF", lowerAlpha2: "af", code: 93 },
  {
    en: "Antigua and Barbuda",
    ja: "アンティグア・バーブーダ",
    alpha2: "AG",
    lowerAlpha2: "ag",
    code: 1,
  },
  { en: "Anguilla", ja: "アングイラ", alpha2: "AI", lowerAlpha2: "ai", code: 1 },
  { en: "Albania", ja: "アルバニア", alpha2: "AL", lowerAlpha2: "al", code: 355 },
  { en: "Armenia", ja: "アルメニア", alpha2: "AM", lowerAlpha2: "am", code: 374 },
  { en: "Angola", ja: "アンゴラ", alpha2: "AO", lowerAlpha2: "ao", code: 244 },
  { en: "Antarctica", ja: "南極大陸", alpha2: "AQ", lowerAlpha2: "aq", code: 672 },
  { en: "Argentina", ja: "アルゼンチン", alpha2: "AR", lowerAlpha2: "ar", code: 54 },
  { en: "American Samoa", ja: "米領サモア", alpha2: "AS", lowerAlpha2: "as", code: 1 },
  { en: "Austria", ja: "オーストリア", alpha2: "AT", lowerAlpha2: "at", code: 43 },
  { en: "Australia", ja: "オーストラリア連邦", alpha2: "AU", lowerAlpha2: "au", code: 61 },
  { en: "Aruba", ja: "アルーバ", alpha2: "AW", lowerAlpha2: "aw", code: 297 },
  { en: "Åland Islands", ja: "オーランド諸島", alpha2: "AX", lowerAlpha2: "ax", code: 358 },
  { en: "Azerbaijan", ja: "アゼルバイジャン", alpha2: "AZ", lowerAlpha2: "az", code: 994 },
  {
    en: "Bosnia and Herzegovina",
    ja: "ボスニア・ヘルツェゴビナ",
    alpha2: "BA",
    lowerAlpha2: "ba",
    code: 387,
  },
  { en: "Barbados", ja: "バルバドス", alpha2: "BB", lowerAlpha2: "bb", code: 1 },
  { en: "Bangladesh", ja: "バングラデシュ", alpha2: "BD", lowerAlpha2: "bd", code: 880 },
  { en: "Belgium", ja: "ベルギー", alpha2: "BE", lowerAlpha2: "be", code: 32 },
  { en: "Burkina Faso", ja: "ブルキナファソ", alpha2: "BF", lowerAlpha2: "bf", code: 226 },
  { en: "Bulgaria", ja: "ブルガリア", alpha2: "BG", lowerAlpha2: "bg", code: 359 },
  { en: "Bahrain", ja: "バーレーン", alpha2: "BH", lowerAlpha2: "bh", code: 973 },
  { en: "Burundi", ja: "ブルンジ", alpha2: "BI", lowerAlpha2: "bi", code: 257 },
  { en: "Benin", ja: "ベナン", alpha2: "BJ", lowerAlpha2: "bj", code: 229 },
  { en: "Saint Barthélemy", ja: "サンバルテルミ", alpha2: "BL", lowerAlpha2: "bl", code: 590 },
  { en: "Bermuda", ja: "バーミューダ", alpha2: "BM", lowerAlpha2: "bm", code: 1 },
  {
    en: "Brunei Darussalam",
    ja: "ブルネイ・ダルサラーム国",
    alpha2: "BN",
    lowerAlpha2: "bn",
    code: 673,
  },
  { en: "Bolivia", ja: "ボリビア", alpha2: "BO", lowerAlpha2: "bo", code: 591 },
  {
    en: "Bonaire, Sint Eustatius and Saba",
    ja: "ボネール、シントユースタティウス及びサバ",
    alpha2: "BQ",
    lowerAlpha2: "bq",
    code: 599,
  },
  { en: "Brazil", ja: "ブラジル", alpha2: "BR", lowerAlpha2: "br", code: 55 },
  { en: "Bahamas", ja: "バハマ", alpha2: "BS", lowerAlpha2: "bs", code: 1 },
  { en: "Bhutan", ja: "ブータン", alpha2: "BT", lowerAlpha2: "bt", code: 975 },
  { en: "Bouvet Island", ja: "ブーベ島", alpha2: "BV", lowerAlpha2: "bv", code: 47 },
  { en: "Botswana", ja: "ボツワナ", alpha2: "BW", lowerAlpha2: "bw", code: 267 },
  { en: "Belarus", ja: "ベラルーシ", alpha2: "BY", lowerAlpha2: "by", code: 375 },
  { en: "Belize", ja: "ベリーズ", alpha2: "BZ", lowerAlpha2: "bz", code: 501 },
  { en: "Canada", ja: "カナダ", alpha2: "CA", lowerAlpha2: "ca", code: 1 },
  {
    en: "Cocos (Keeling) Islands",
    ja: "ココス (キーリング) 諸島",
    alpha2: "CC",
    lowerAlpha2: "cc",
    code: 61,
  },
  {
    en: "Congo, The Democratic Republic of the",
    ja: "コンゴ民主共和国",
    alpha2: "CD",
    lowerAlpha2: "cd",
    code: 243,
  },
  {
    en: "Central African Republic",
    ja: "中央アフリカ共和国",
    alpha2: "CF",
    lowerAlpha2: "cf",
    code: 236,
  },
  { en: "Congo", ja: "コンゴ", alpha2: "CG", lowerAlpha2: "cg", code: 242 },
  { en: "Switzerland", ja: "スイス", alpha2: "CH", lowerAlpha2: "ch", code: 41 },
  { en: "Côte d'Ivoire", ja: "コートジボワール", alpha2: "CI", lowerAlpha2: "ci", code: 225 },
  { en: "Cook Islands", ja: "クック諸島", alpha2: "CK", lowerAlpha2: "ck", code: 682 },
  { en: "Chile", ja: "チリ", alpha2: "CL", lowerAlpha2: "cl", code: 56 },
  { en: "Cameroon", ja: "カメルーン", alpha2: "CM", lowerAlpha2: "cm", code: 237 },
  { en: "China", ja: "中国", alpha2: "CN", lowerAlpha2: "cn", code: 86 },
  { en: "Colombia", ja: "コロンビア", alpha2: "CO", lowerAlpha2: "co", code: 57 },
  { en: "Costa Rica", ja: "コスタリカ", alpha2: "CR", lowerAlpha2: "cr", code: 506 },
  { en: "Cuba", ja: "キューバ", alpha2: "CU", lowerAlpha2: "cu", code: 53 },
  { en: "Cabo Verde", ja: "カーボヴェルデ", alpha2: "CV", lowerAlpha2: "cv", code: 238 },
  { en: "Curaçao", ja: "キュラソー", alpha2: "CW", lowerAlpha2: "cw", code: 599 },
  { en: "Christmas Island", ja: "クリスマス島", alpha2: "CX", lowerAlpha2: "cx", code: 61 },
  { en: "Cyprus", ja: "キプロス", alpha2: "CY", lowerAlpha2: "cy", code: 357 },
  { en: "Czechia", ja: "チェコ共和国", alpha2: "CZ", lowerAlpha2: "cz", code: 420 },
  { en: "Germany", ja: "ドイツ", alpha2: "DE", lowerAlpha2: "de", code: 49 },
  { en: "Djibouti", ja: "ジブチ", alpha2: "DJ", lowerAlpha2: "dj", code: 253 },
  { en: "Denmark", ja: "デンマーク", alpha2: "DK", lowerAlpha2: "dk", code: 45 },
  { en: "Dominica", ja: "ドミニカ", alpha2: "DM", lowerAlpha2: "dm", code: 1 },
  { en: "Dominican Republic", ja: "ドミニカ共和国", alpha2: "DO", lowerAlpha2: "do", code: 1 },
  { en: "Algeria", ja: "アルジェリア", alpha2: "DZ", lowerAlpha2: "dz", code: 213 },
  { en: "Ecuador", ja: "エクアドル", alpha2: "EC", lowerAlpha2: "ec", code: 593 },
  { en: "Estonia", ja: "エストニア", alpha2: "EE", lowerAlpha2: "ee", code: 372 },
  { en: "Egypt", ja: "エジプト", alpha2: "EG", lowerAlpha2: "eg", code: 20 },
  { en: "Western Sahara", ja: "西サハラ", alpha2: "EH", lowerAlpha2: "eh", code: 212 },
  { en: "Eritrea", ja: "エリトリア国", alpha2: "ER", lowerAlpha2: "er", code: 291 },
  { en: "Spain", ja: "スペイン", alpha2: "ES", lowerAlpha2: "es", code: 34 },
  { en: "Ethiopia", ja: "エチオピア", alpha2: "ET", lowerAlpha2: "et", code: 251 },
  { en: "Finland", ja: "フィンランド", alpha2: "FI", lowerAlpha2: "fi", code: 358 },
  { en: "Fiji", ja: "フィジー", alpha2: "FJ", lowerAlpha2: "fj", code: 679 },
  {
    en: "Falkland Islands (Malvinas)",
    ja: "フォークランド諸島 (マルビナス)",
    alpha2: "FK",
    lowerAlpha2: "fk",
    code: 500,
  },
  {
    en: "Micronesia, Federated States of",
    ja: "ミクロネシア連邦",
    alpha2: "FM",
    lowerAlpha2: "fm",
    code: 691,
  },
  { en: "Faroe Islands", ja: "フェロー諸島", alpha2: "FO", lowerAlpha2: "fo", code: 298 },
  { en: "France", ja: "フランス", alpha2: "FR", lowerAlpha2: "fr", code: 33 },
  { en: "Gabon", ja: "ガボン", alpha2: "GA", lowerAlpha2: "ga", code: 241 },
  { en: "United Kingdom", ja: "英国", alpha2: "GB", lowerAlpha2: "gb", code: 44 },
  { en: "Grenada", ja: "グレナダ", alpha2: "GD", lowerAlpha2: "gd", code: 1 },
  { en: "Georgia", ja: "グルジア", alpha2: "GE", lowerAlpha2: "ge", code: 995 },
  { en: "French Guiana", ja: "仏領ギアナ", alpha2: "GF", lowerAlpha2: "gf", code: 594 },
  { en: "Guernsey", ja: "ガーンジー", alpha2: "GG", lowerAlpha2: "gg", code: 44 },
  { en: "Ghana", ja: "ガーナ", alpha2: "GH", lowerAlpha2: "gh", code: 233 },
  { en: "Gibraltar", ja: "ジブラルタル", alpha2: "GI", lowerAlpha2: "gi", code: 350 },
  { en: "Greenland", ja: "グリーンランド", alpha2: "GL", lowerAlpha2: "gl", code: 299 },
  { en: "Gambia", ja: "ガンビア", alpha2: "GM", lowerAlpha2: "gm", code: 220 },
  { en: "Guinea", ja: "ギニア", alpha2: "GN", lowerAlpha2: "gn", code: 224 },
  { en: "Guadeloupe", ja: "グアドループ", alpha2: "GP", lowerAlpha2: "gp", code: 590 },
  { en: "Equatorial Guinea", ja: "赤道ギニア", alpha2: "GQ", lowerAlpha2: "gq", code: 240 },
  { en: "Greece", ja: "ギリシャ", alpha2: "GR", lowerAlpha2: "gr", code: 30 },
  {
    en: "South Georgia and the South Sandwich Islands",
    ja: "サウスジョージア及びサウスサンドウィッチ諸島",
    alpha2: "GS",
    lowerAlpha2: "gs",
    code: 500,
  },
  { en: "Guatemala", ja: "グアテマラ", alpha2: "GT", lowerAlpha2: "gt", code: 502 },
  { en: "Guam", ja: "グアム", alpha2: "GU", lowerAlpha2: "gu", code: 1 },
  { en: "Guinea-Bissau", ja: "ギニアビサウ", alpha2: "GW", lowerAlpha2: "gw", code: 245 },
  { en: "Guyana", ja: "ガイアナ", alpha2: "GY", lowerAlpha2: "gy", code: 592 },
  { en: "Hong Kong", ja: "香港", alpha2: "HK", lowerAlpha2: "hk", code: 852 },
  {
    en: "Heard Island and McDonald Islands",
    ja: "ハード島及びマクドナルド諸島",
    alpha2: "HM",
    lowerAlpha2: "hm",
    code: 672,
  },
  { en: "Honduras", ja: "ホンジュラス", alpha2: "HN", lowerAlpha2: "hn", code: 504 },
  { en: "Croatia", ja: "クロアチア", alpha2: "HR", lowerAlpha2: "hr", code: 385 },
  { en: "Haiti", ja: "ハイチ", alpha2: "HT", lowerAlpha2: "ht", code: 509 },
  { en: "Hungary", ja: "ハンガリー", alpha2: "HU", lowerAlpha2: "hu", code: 36 },
  { en: "Indonesia", ja: "インドネシア", alpha2: "ID", lowerAlpha2: "id", code: 62 },
  { en: "Ireland", ja: "アイルランド", alpha2: "IE", lowerAlpha2: "ie", code: 353 },
  { en: "Israel", ja: "イスラエル", alpha2: "IL", lowerAlpha2: "il", code: 972 },
  { en: "Isle of Man", ja: "マン島", alpha2: "IM", lowerAlpha2: "im", code: 44 },
  { en: "India", ja: "インド", alpha2: "IN", lowerAlpha2: "in", code: 91 },
  {
    en: "British Indian Ocean Territory",
    ja: "英国インド洋領土",
    alpha2: "IO",
    lowerAlpha2: "io",
    code: 246,
  },
  { en: "Iraq", ja: "イラク", alpha2: "IQ", lowerAlpha2: "iq", code: 964 },
  { en: "Iran", ja: "イラン・イスラム共和国", alpha2: "IR", lowerAlpha2: "ir", code: 98 },
  { en: "Iceland", ja: "アイスランド", alpha2: "IS", lowerAlpha2: "is", code: 354 },
  { en: "Italy", ja: "イタリア", alpha2: "IT", lowerAlpha2: "it", code: 39 },
  { en: "Jersey", ja: "ジャージー", alpha2: "JE", lowerAlpha2: "je", code: 44 },
  { en: "Jamaica", ja: "ジャマイカ", alpha2: "JM", lowerAlpha2: "jm", code: 1 },
  { en: "Jordan", ja: "ヨルダン", alpha2: "JO", lowerAlpha2: "jo", code: 962 },
  { en: "Japan", ja: "日本", alpha2: "JP", lowerAlpha2: "jp", code: 81 },
  { en: "Kenya", ja: "ケニア", alpha2: "KE", lowerAlpha2: "ke", code: 254 },
  { en: "Kyrgyzstan", ja: "キルギスタン", alpha2: "KG", lowerAlpha2: "kg", code: 996 },
  { en: "Cambodia", ja: "カンボジア", alpha2: "KH", lowerAlpha2: "kh", code: 855 },
  { en: "Kiribati", ja: "キリバス", alpha2: "KI", lowerAlpha2: "ki", code: 686 },
  { en: "Comoros", ja: "コモロ", alpha2: "KM", lowerAlpha2: "km", code: 269 },
  {
    en: "Saint Kitts and Nevis",
    ja: "セントクリストファー・ネーヴィス",
    alpha2: "KN",
    lowerAlpha2: "kn",
    code: 1,
  },
  { en: "North Korea", ja: "朝鮮民主主義人民共和国", alpha2: "KP", lowerAlpha2: "kp", code: 850 },
  { en: "South Korea", ja: "大韓民国 (韓国)", alpha2: "KR", lowerAlpha2: "kr", code: 82 },
  { en: "Kuwait", ja: "クウェート", alpha2: "KW", lowerAlpha2: "kw", code: 965 },
  { en: "Cayman Islands", ja: "ケイマン諸島", alpha2: "KY", lowerAlpha2: "ky", code: 1 },
  { en: "Kazakhstan", ja: "カザフスタン", alpha2: "KZ", lowerAlpha2: "kz", code: 7 },
  {
    en: "Lao People's Democratic Republic",
    ja: "ラオス人民民主共和国",
    alpha2: "LA",
    lowerAlpha2: "la",
    code: 856,
  },
  { en: "Lebanon", ja: "レバノン", alpha2: "LB", lowerAlpha2: "lb", code: 961 },
  { en: "Saint Lucia", ja: "セントルシア", alpha2: "LC", lowerAlpha2: "lc", code: 1 },
  { en: "Liechtenstein", ja: "リヒテンシュタイン", alpha2: "LI", lowerAlpha2: "li", code: 423 },
  { en: "Sri Lanka", ja: "スリランカ", alpha2: "LK", lowerAlpha2: "lk", code: 94 },
  { en: "Liberia", ja: "リベリア", alpha2: "LR", lowerAlpha2: "lr", code: 231 },
  { en: "Lesotho", ja: "レソト", alpha2: "LS", lowerAlpha2: "ls", code: 266 },
  { en: "Lithuania", ja: "リトアニア", alpha2: "LT", lowerAlpha2: "lt", code: 370 },
  { en: "Luxembourg", ja: "ルクセンブルク", alpha2: "LU", lowerAlpha2: "lu", code: 352 },
  { en: "Latvia", ja: "ラトビア", alpha2: "LV", lowerAlpha2: "lv", code: 371 },
  { en: "Libya", ja: "リビア", alpha2: "LY", lowerAlpha2: "ly", code: 218 },
  { en: "Morocco", ja: "モロッコ", alpha2: "MA", lowerAlpha2: "ma", code: 212 },
  { en: "Monaco", ja: "モナコ", alpha2: "MC", lowerAlpha2: "mc", code: 377 },
  { en: "Moldova", ja: "モルドバ", alpha2: "MD", lowerAlpha2: "md", code: 373 },
  { en: "Montenegro", ja: "モンテネグロ", alpha2: "ME", lowerAlpha2: "me", code: 382 },
  {
    en: "Saint Martin (French part)",
    ja: "サンマルタン (仏領)",
    alpha2: "MF",
    lowerAlpha2: "mf",
    code: 590,
  },
  { en: "Madagascar", ja: "マダガスカル", alpha2: "MG", lowerAlpha2: "mg", code: 261 },
  { en: "Marshall Islands", ja: "マーシャル諸島", alpha2: "MH", lowerAlpha2: "mh", code: 692 },
  { en: "North Macedonia", ja: "北マケドニア共和国", alpha2: "MK", lowerAlpha2: "mk", code: 389 },
  { en: "Mali", ja: "マリ", alpha2: "ML", lowerAlpha2: "ml", code: 223 },
  { en: "Myanmar", ja: "ミャンマー", alpha2: "MM", lowerAlpha2: "mm", code: 95 },
  { en: "Mongolia", ja: "モンゴル国", alpha2: "MN", lowerAlpha2: "mn", code: 976 },
  { en: "Macao", ja: "マカオ", alpha2: "MO", lowerAlpha2: "mo", code: 853 },
  {
    en: "Northern Mariana Islands",
    ja: "北マリアナ諸島",
    alpha2: "MP",
    lowerAlpha2: "mp",
    code: 1,
  },
  { en: "Martinique", ja: "マルティニーク", alpha2: "MQ", lowerAlpha2: "mq", code: 596 },
  { en: "Mauritania", ja: "モーリタニア", alpha2: "MR", lowerAlpha2: "mr", code: 222 },
  { en: "Montserrat", ja: "モントセラト", alpha2: "MS", lowerAlpha2: "ms", code: 1 },
  { en: "Malta", ja: "マルタ", alpha2: "MT", lowerAlpha2: "mt", code: 356 },
  { en: "Mauritius", ja: "モーリシャス", alpha2: "MU", lowerAlpha2: "mu", code: 230 },
  { en: "Maldives", ja: "モルディブ", alpha2: "MV", lowerAlpha2: "mv", code: 960 },
  { en: "Malawi", ja: "マラウイ", alpha2: "MW", lowerAlpha2: "mw", code: 265 },
  { en: "Mexico", ja: "メキシコ", alpha2: "MX", lowerAlpha2: "mx", code: 52 },
  { en: "Malaysia", ja: "マレーシア", alpha2: "MY", lowerAlpha2: "my", code: 60 },
  { en: "Mozambique", ja: "モザンビーク", alpha2: "MZ", lowerAlpha2: "mz", code: 258 },
  { en: "Namibia", ja: "ナミビア", alpha2: "NA", lowerAlpha2: "na", code: 264 },
  { en: "New Caledonia", ja: "ニューカレドニア", alpha2: "NC", lowerAlpha2: "nc", code: 687 },
  { en: "Niger", ja: "ニジェール", alpha2: "NE", lowerAlpha2: "ne", code: 227 },
  { en: "Norfolk Island", ja: "ノーフォーク島", alpha2: "NF", lowerAlpha2: "nf", code: 672 },
  { en: "Nigeria", ja: "ナイジェリア", alpha2: "NG", lowerAlpha2: "ng", code: 234 },
  { en: "Nicaragua", ja: "ニカラグア", alpha2: "NI", lowerAlpha2: "ni", code: 505 },
  { en: "Netherlands", ja: "オランダ", alpha2: "NL", lowerAlpha2: "nl", code: 31 },
  { en: "Norway", ja: "ノルウェー", alpha2: "NO", lowerAlpha2: "no", code: 47 },
  { en: "Nepal", ja: "ネパール", alpha2: "NP", lowerAlpha2: "np", code: 977 },
  { en: "Nauru", ja: "ナウル", alpha2: "NR", lowerAlpha2: "nr", code: 674 },
  { en: "Niue", ja: "ニウエ", alpha2: "NU", lowerAlpha2: "nu", code: 683 },
  { en: "New Zealand", ja: "ニュージーランド", alpha2: "NZ", lowerAlpha2: "nz", code: 64 },
  { en: "Oman", ja: "オマーン", alpha2: "OM", lowerAlpha2: "om", code: 968 },
  { en: "Panama", ja: "パナマ", alpha2: "PA", lowerAlpha2: "pa", code: 507 },
  { en: "Peru", ja: "ペルー", alpha2: "PE", lowerAlpha2: "pe", code: 51 },
  { en: "French Polynesia", ja: "仏領ポリネシア", alpha2: "PF", lowerAlpha2: "pf", code: 689 },
  { en: "Papua New Guinea", ja: "パプアニューギニア", alpha2: "PG", lowerAlpha2: "pg", code: 675 },
  { en: "Philippines", ja: "フィリピン", alpha2: "PH", lowerAlpha2: "ph", code: 63 },
  { en: "Pakistan", ja: "パキスタン", alpha2: "PK", lowerAlpha2: "pk", code: 92 },
  { en: "Poland", ja: "ポーランド", alpha2: "PL", lowerAlpha2: "pl", code: 48 },
  {
    en: "Saint Pierre and Miquelon",
    ja: "サンピエール及びミクロン",
    alpha2: "PM",
    lowerAlpha2: "pm",
    code: 508,
  },
  { en: "Pitcairn", ja: "ピトケアン", alpha2: "PN", lowerAlpha2: "pn", code: 64 },
  { en: "Puerto Rico", ja: "プエルトリコ", alpha2: "PR", lowerAlpha2: "pr", code: 1 },
  { en: "Palestine, State of", ja: "パレスチナ", alpha2: "PS", lowerAlpha2: "ps", code: 970 },
  { en: "Portugal", ja: "ポルトガル", alpha2: "PT", lowerAlpha2: "pt", code: 351 },
  { en: "Palau", ja: "パラオ", alpha2: "PW", lowerAlpha2: "pw", code: 680 },
  { en: "Paraguay", ja: "パラグアイ", alpha2: "PY", lowerAlpha2: "py", code: 595 },
  { en: "Qatar", ja: "カタール", alpha2: "QA", lowerAlpha2: "qa", code: 974 },
  { en: "Réunion", ja: "レユニオン", alpha2: "RE", lowerAlpha2: "re", code: 262 },
  { en: "Romania", ja: "ルーマニア", alpha2: "RO", lowerAlpha2: "ro", code: 40 },
  { en: "Serbia", ja: "セルビア", alpha2: "RS", lowerAlpha2: "rs", code: 381 },
  { en: "Russian Federation", ja: "ロシア連邦", alpha2: "RU", lowerAlpha2: "ru", code: 7 },
  { en: "Rwanda", ja: "ルワンダ", alpha2: "RW", lowerAlpha2: "rw", code: 250 },
  { en: "Saudi Arabia", ja: "サウジアラビア", alpha2: "SA", lowerAlpha2: "sa", code: 966 },
  { en: "Solomon Islands", ja: "ソロモン諸島", alpha2: "SB", lowerAlpha2: "sb", code: 677 },
  { en: "Seychelles", ja: "セーシェル", alpha2: "SC", lowerAlpha2: "sc", code: 248 },
  { en: "Sudan", ja: "スーダン", alpha2: "SD", lowerAlpha2: "sd", code: 249 },
  { en: "Sweden", ja: "スウェーデン", alpha2: "SE", lowerAlpha2: "se", code: 46 },
  { en: "Singapore", ja: "シンガポール", alpha2: "SG", lowerAlpha2: "sg", code: 65 },
  {
    en: "Saint Helena, Ascension and Tristan da Cunha",
    ja: "セントヘレナ、アセンション及びトリスタン・ダ・クーニャ",
    alpha2: "SH",
    lowerAlpha2: "sh",
    code: 290,
  },
  { en: "Slovenia", ja: "スロベニア", alpha2: "SI", lowerAlpha2: "si", code: 386 },
  {
    en: "Svalbard and Jan Mayen",
    ja: "スヴァールバル及びヤンマイエン",
    alpha2: "SJ",
    lowerAlpha2: "sj",
    code: 47,
  },
  { en: "Slovakia", ja: "スロバキア", alpha2: "SK", lowerAlpha2: "sk", code: 421 },
  { en: "Sierra Leone", ja: "シエラレオネ", alpha2: "SL", lowerAlpha2: "sl", code: 232 },
  { en: "San Marino", ja: "サンマリノ", alpha2: "SM", lowerAlpha2: "sm", code: 378 },
  { en: "Senegal", ja: "セネガル", alpha2: "SN", lowerAlpha2: "sn", code: 221 },
  { en: "Somalia", ja: "ソマリア", alpha2: "SO", lowerAlpha2: "so", code: 252 },
  { en: "Suriname", ja: "スリナム", alpha2: "SR", lowerAlpha2: "sr", code: 597 },
  { en: "South Sudan", ja: "南スーダン", alpha2: "SS", lowerAlpha2: "ss", code: 211 },
  {
    en: "Sao Tome and Principe",
    ja: "サントメ・プリンシペ",
    alpha2: "ST",
    lowerAlpha2: "st",
    code: 239,
  },
  { en: "El Salvador", ja: "エルサルバドル", alpha2: "SV", lowerAlpha2: "sv", code: 503 },
  {
    en: "Sint Maarten (Dutch part)",
    ja: "サンマルタン (オランダ領)",
    alpha2: "SX",
    lowerAlpha2: "sx",
    code: 1,
  },
  {
    en: "Syrian Arab Republic",
    ja: "シリア・アラブ共和国",
    alpha2: "SY",
    lowerAlpha2: "sy",
    code: 963,
  },
  { en: "Eswatini", ja: "エスワティニ王国", alpha2: "SZ", lowerAlpha2: "sz", code: 268 },
  {
    en: "Turks and Caicos Islands",
    ja: "タークス及びカイコス諸島",
    alpha2: "TC",
    lowerAlpha2: "tc",
    code: 1,
  },
  { en: "Chad", ja: "チャド", alpha2: "TD", lowerAlpha2: "td", code: 235 },
  {
    en: "French Southern Territories",
    ja: "フランス南方領土",
    alpha2: "TF",
    lowerAlpha2: "tf",
    code: 262,
  },
  { en: "Togo", ja: "トーゴ", alpha2: "TG", lowerAlpha2: "tg", code: 228 },
  { en: "Thailand", ja: "タイ", alpha2: "TH", lowerAlpha2: "th", code: 66 },
  { en: "Tajikistan", ja: "タジキスタン", alpha2: "TJ", lowerAlpha2: "tj", code: 992 },
  { en: "Tokelau", ja: "トケラウ", alpha2: "TK", lowerAlpha2: "tk", code: 690 },
  { en: "Timor-Leste", ja: "東ティモール", alpha2: "TL", lowerAlpha2: "tl", code: 670 },
  { en: "Turkmenistan", ja: "トルクメニスタン", alpha2: "TM", lowerAlpha2: "tm", code: 993 },
  { en: "Tunisia", ja: "チュニジア", alpha2: "TN", lowerAlpha2: "tn", code: 216 },
  { en: "Tonga", ja: "トンガ", alpha2: "TO", lowerAlpha2: "to", code: 676 },
  { en: "Türkiye", ja: "トルコ", alpha2: "TR", lowerAlpha2: "tr", code: 90 },
  {
    en: "Trinidad and Tobago",
    ja: "トリニダード・トバゴ",
    alpha2: "TT",
    lowerAlpha2: "tt",
    code: 1,
  },
  { en: "Tuvalu", ja: "ツバル", alpha2: "TV", lowerAlpha2: "tv", code: 688 },
  { en: "Taiwan", ja: "台湾", alpha2: "TW", lowerAlpha2: "tw", code: 886 },
  { en: "Tanzania", ja: "タンザニア", alpha2: "TZ", lowerAlpha2: "tz", code: 255 },
  { en: "Ukraine", ja: "ウクライナ", alpha2: "UA", lowerAlpha2: "ua", code: 380 },
  { en: "Uganda", ja: "ウガンダ", alpha2: "UG", lowerAlpha2: "ug", code: 256 },
  {
    en: "United States Minor Outlying Islands",
    ja: "アメリカ合衆国外諸島",
    alpha2: "UM",
    lowerAlpha2: "um",
    code: 1,
  },
  { en: "United States", ja: "米国", alpha2: "US", lowerAlpha2: "us", code: 1 },
  { en: "Uruguay", ja: "ウルグアイ", alpha2: "UY", lowerAlpha2: "uy", code: 598 },
  { en: "Uzbekistan", ja: "ウズベキスタン", alpha2: "UZ", lowerAlpha2: "uz", code: 998 },
  {
    en: "Holy See (Vatican City State)",
    ja: "聖庁 (バチカン市国)",
    alpha2: "VA",
    lowerAlpha2: "va",
    code: 39,
  },
  {
    en: "Saint Vincent and the Grenadines",
    ja: "セントビンセント及びグレナディーン諸島",
    alpha2: "VC",
    lowerAlpha2: "vc",
    code: 1,
  },
  { en: "Venezuela", ja: "ベネズエラ", alpha2: "VE", lowerAlpha2: "ve", code: 58 },
  {
    en: "Virgin Islands, British",
    ja: "英領ヴァージン諸島",
    alpha2: "VG",
    lowerAlpha2: "vg",
    code: 1,
  },
  {
    en: "Virgin Islands, U.S.",
    ja: "米領ヴァージン諸島",
    alpha2: "VI",
    lowerAlpha2: "vi",
    code: 1,
  },
  { en: "Vietnam", ja: "ベトナム", alpha2: "VN", lowerAlpha2: "vn", code: 84 },
  { en: "Vanuatu", ja: "バヌアツ", alpha2: "VU", lowerAlpha2: "vu", code: 678 },
  { en: "Wallis and Futuna", ja: "ワリー及びフテュナ", alpha2: "WF", lowerAlpha2: "wf", code: 681 },
  { en: "Samoa", ja: "サモア", alpha2: "WS", lowerAlpha2: "ws", code: 685 },
  { en: "Yemen", ja: "イエメン", alpha2: "YE", lowerAlpha2: "ye", code: 967 },
  { en: "Mayotte", ja: "マヨット", alpha2: "YT", lowerAlpha2: "yt", code: 262 },
  { en: "South Africa", ja: "南アフリカ", alpha2: "ZA", lowerAlpha2: "za", code: 27 },
  { en: "Zambia", ja: "ザンビア", alpha2: "ZM", lowerAlpha2: "zm", code: 260 },
  { en: "Zimbabwe", ja: "ジンバブエ", alpha2: "ZW", lowerAlpha2: "zw", code: 263 },
];

export const countries = (local: "en" | "ja") => {
  return COUNTRIES.map((country) => {
    const label = country[local];
    const firstLetter = label[0].toUpperCase();
    return {
      label,
      firstLetter,
      alpha2: country.alpha2,
      lowerAlpha2: country.lowerAlpha2,
      code: country.code,
      phone: `+${country.code}`,
    };
  });
};

export type Countries = ReturnType<typeof countries>[number];
